apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-app
    platform.environment: staging
spec:
  project: platform-app-project
  source:
    repoURL: https://gitlab.com/user/platform-gitops.git
    targetRevision: main
    path: charts/platform-app
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-staging
