replicaCount: 2

image:
  tag: "staging-latest"
  digest: ""

resources:
  requests:
    cpu: "150m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  data:
    APP_ENV: staging

env:
  APP_LOG_LEVEL: info

autoscaling:
  enabled: false
